name: Project tests
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t gftextcaptcha
      - run: docker save gftextcaptcha | gzip - > gftextcaptcha.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: gftextcaptcha.tar.gz
          retention-days: 1
  unit-tests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docker-image
      - run: zcat gftextcaptcha.tar.gz | docker load
      - run: docker run --rm gftextcaptcha test
  lint:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docker-image
      - run: zcat gftextcaptcha.tar.gz | docker load
      - run: docker run --rm gftextcaptcha lint
